### ISSUE TITLE
WNBA pbp/box scores needing update

### ISSUE THREAD

**Issue by dbaggot3** [sportsdataverse/wehoop#21]
**Describe the bug**
Hi there! Not sure if this is the best method of contacting, but it doesn't look like the WNBA pbp and box score data for this season has been updated since Saturday (5/7). As well, it looks like a handful of the games that are listed in the box scores/pbp have been dated incorrectly.

Is there a fix for this on the user end? Thanks in advance for your help!

**Comment by saiemgilani** [comment]
Just updated the data repo. There's some things I need to do with lubridate to bring things to the correct timezone tbh. I'm leaving this issue open to remind myself

**Comment by dbaggot3** [comment]
Awesome, thank you for the quick response and fix!

**Comment by saiemgilani** [comment]
I realized much later that this was in fact still an issue with the data not updating. I have fixed the data not getting updated, I have not fixed the timezone issue to at least bring it to eastern time
