### ISSUE TITLE
Not A Bug - Is 2021-2022 data no longer available?

### ISSUE THREAD

**Issue by jrbarber37** [sportsdataverse/wehoop#29]
**Describe the bug**
I ran the same code I ran earlier to pull 2021-2022 data for Cornell and I received no data.  I did the same for Fairfield and got back only their one NCAA Tournament game.

Thank you.

**Comment by saiemgilani** [comment]
Super weird, will look into why that's happening

**Comment by jrbarber37** [comment]
Thank you.

**Comment by saiemgilani** [comment]
Whatever is available should be available again. Around 5347 games of pbp, around 5500 with team box and player box scores. Some api issue was restricting the number of events being populated

Note to Dev todo:
Evidently the groups=50 parameter isn't producing events with the scoreboard for 2021 thru 2023. May need to switch to using header scoreboard or experimenting as the season progresses
