### ISSUE TITLE
WNBA pbp error for 2023

### ISSUE THREAD

**Issue by jmhyman-su** [sportsdataverse/wehoop#31]
**Describe the bug**
The load_wnba_pbp function does not appear to work yet for the 2023 season

**To Reproduce**
wehoop::load_wnba_pbp(seasons = 2023) returns:

Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/wehoop-data/main/wnba/pbp/rds/play_by_play_2023.rds': HTTP status was '404 Not Found'

**Expected behavior**
Older seasons still work with the function

**Additional context**
Appreciate any help, thanks!

**Comment by iksnizez** [comment]
Any luck getting 2023 data?

**Comment by aaronmorrisNC** [comment]
I haven’t tested again.  Was waiting for the bug ticket to be updated.

-Aaron

**Comment by andreweatherman** [comment]
All `load_wnba_x` functions should work now 

cc: @jmhyman-su, @iksnizez, @aaronmorrisNC

**Comment by saiemgilani** [comment]
Wait this issue wasn't related to the releases not getting updated, these folks needed to move to the development version of the package. The data was being updated.

Run:
```r
remotes::install_github("sportsdataverse/wehoop")
```
Refresh your session.

We need to reverse #34

**Comment by saiemgilani** [comment]
closed by 29c4ea7e3baaf91235336753238abf597a6fe749
