### ISSUE TITLE
load_wbb_schedule()

### ISSUE THREAD

**Issue by hoopsadoops** [sportsdataverse/wehoop#35]
Receiving the following error, trying to run
Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from <https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds> 

Will it work once the season has begun?

Thanks

**Comment by hoopsadoops** [comment]
As I see it, there is also no data for any 2024 seasons as of yet?? NBA i get a similar message
most_recent_nba_season()
[1] 2024
> load_nba_team_box(2024)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── hoopR 1.8.0 ──
# A tibble: 0 × 0
Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/nba/team_box/rds/team_box_2024.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from <https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/nba/team_box/rds/team_box_2024.rds>

**Comment by saiemgilani** [comment]
While this issue appears to mostly talk about `{hoopR}`, the issues relayed were similarly present with `{wehoop}`
Please run the following code to update to the development versions of both packages:

```r
remotes::install_github("sportsdataverse/wehoop")
remotes::install_github("sportsdataverse/hoopR")
```

The data for all current and on-going seasons should now be updated nightly

**Comment by hoopsadoops** [comment]
wehoop now works, hoopR not though

df<-load_mbb_schedule(2024)
Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from <https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds>

**Comment by saiemgilani** [comment]
> wehoop now works, hoopR not though
> 
> df<-load_mbb_schedule(2024) Warning messages: 1: In readRDS(con) : cannot open URL 'https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds': HTTP status was '404 Not Found' 2: Failed to readRDS from https://raw.githubusercontent.com/sportsdataverse/hoopR-data/main/mbb/schedules/rds/mbb_schedule_2024.rds

Update your package:
```r
remotes::install_github("sportsdataverse/hoopR")
```
